project:
  type: website
  output-dir: .

website:
  title: "Tommy's Blog"
  site-url: https://khuutommy.github.io
  google-analytics: "G-Z2W4E7B4M8"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/khuutommy
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css






